services:
  postgres:
    image: postgres:15
    restart: always
    container_name: "machines-managment-db"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
